name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install platform dependencies
      run: |
        sudo apt-get update
        # Yahan humne libtool, gettext, aur m4 tools ko add kiya hai jo libffi ke liye zaroori hain
        sudo apt-get install -y libsqlite3-dev sqlite3 bzip2 libbz2-dev libssl-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev libncursesw5-dev libffi-dev uuid-dev tar openjdk-17-jdk unzip autoconf libtool pkg-config zlib1g-dev gettext m4 libtool-bin

    - name: Install Buildozer and Dependencies
      run: |
        pip install --upgrade pip
        pip install Cython==0.29.33 buildozer python-for-android

    - name: Pre-setup Android SDK Manager for Buildozer
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -q
        unzip -q commandlinetools-linux-9477386_latest.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
        rm commandlinetools-linux-9477386_latest.zip
        
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        
        mkdir -p ~/.buildozer/android/platform/android-sdk/tools/bin
        ln -s ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager ~/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager
        
        echo -e "\n244ac7dc2b6901f85741a9d3329313b1e5021f56\n782327e505811d3b4610c3b3bc500e34dd3b95cd\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n9b20bde75b79bef17476568280459eed3103d558\ne9ac30d0b722fc78615c76b3fcb819411714c9c3\nf3191f90b3c4a21596dd403de65e04b96fd991cd\n11144a74a3c3d9224f6b2b46b14a873966db91a4" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Build with Buildozer
      env:
        ANDROID_NDK_HOME: ''
        ANDROID_NDK_ROOT: ''
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Oxygen-Android-APK
        path: bin/*.apk
